### PR TITLE
Added missing CRC for Arcana Heart 2 (ex-Board)

### PR DESCRIPTION
**Pull request by PolybiusExtreme**
Added missing CRC 802f621b for Arcana Heart 2 (ex-Board)

### CODE REVIEW

**Comment by EmiMidnight** [comment]
I tried this and the game refuses to boot for me. Do you have the MD5 or something of the .exe you based this on?

**Comment by PolybiusExtreme** [comment]
The .exe is Arcana Heart 2 v2.1
Name: AH2.exe
Size: 2416640 Bytes (2360 KiB)
CRC64: 8CE79E99E5D5AE01

**Comment by EmiMidnight** [comment]
Seems to be the same exe I was using then. Not sure why, but for me it just crashes immediately without a warning.

**Comment by EmiMidnight** [comment]
I was using an ex-Board profile for this, but I'll try around some more later.

**Pull request closed without merging**
