### PR TITLE
Maximum Tune 5/5DX+ Feature Update (MT5DX+ Story Saving!)

### PR DESCRIPTION
**Pull request by damon-murdoch**
This commit has been tested heavily over the past few weeks, and implements the following:

Maximum Tune 5:
- (Optional) seperate miles and story saving per car
- (Optional) seperate car, miles and story saving per custom name
- Force Full Tune implemented
- Story / Car hex addresses for different properties are documented in the code

The following content needs to be added to the MT5 GameProfile XML file for the new features to work: 

https://pastebin.com/raw/ZLvnJtGe

Maximum Tune 5DX+
- Implemented full story saving
- (Optional) seperate miles and story saving per car
- (Optional) seperate car, miles and story saving per custom name
- Force Full Tune no longer spams, only sets when the car is loaded
- Story / Car hex addresses for different properties are documented in the code

The following content needs to be added to the MT5DX+ GameProfile XML file for all of the new features to work: 

https://pastebin.com/raw/HVuP41j3

Thanks for reading, please let me know if you have any questions or concerns before processing this merge.

### CODE REVIEW

**Comment by Harmmmm** [comment]
That's how you do a PR!👍

**Comment by Poliwrath** [comment]
Great stuff, will likely get merged in a couple days when our build system is working again.
If possible, you could do the profile changes yourself: https://github.com/teknogods/TeknoParrotUI/
Don't forget to read the README and test all changes of course!

**Comment by doomertheboomer** [comment]
pre-test commit

**Comment by doomertheboomer** [comment]
seriously though, thank you for fixing story in 5dx+, i would've never figured it out. will port your changes to the newer 5dx+ version once this gets approved

**Comment by Poliwrath** [comment]
If you're impatient you could probably make a PR to his repo's master branch and it'll show up here once he merges it on his repo

**Comment by damon-murdoch** [comment]
> Great stuff, will likely get merged in a couple days when our build system is working again.
> If possible, you could do the profile changes yourself: https://github.com/teknogods/TeknoParrotUI/
> Don't forget to read the README and test all changes of course!

No worries, thanks for your kind words!

Did not realise TeknoParrotUI was open sourced, I'll do that today. Thanks for letting me know :)

**Comment by doomertheboomer** [comment]
> If you're impatient you could probably make a PR to his repo's master branch and it'll show up here once he merges it on his repo

don't think i could, it'll take a while to redo all my changes + add story and car saving to the newer update too, and i'm also really busy lately so it'll take at least 2 weeks, which this'll be approved by then lol

**Comment by SilenceMinit** [comment]
After trying to update, there will be a conflict with WM6's storage, resulting in invalid WM6's vehicle change and story storage.

**Comment by doomertheboomer** [comment]
you need to rename the files manually, this is openparrot migration's fault and not necessarily the code's fault

**Comment by SilenceMinit** [comment]
> 您需要手动重命名文件，这是openparrot迁移的错误，而不一定是代码的错误
Thank you for your reply. I can save it normally. 6R doesn't seem to work for this method. Is 6R not supported

**Comment by SilenceMinit** [comment]
After a certain test, it is found that saving the story in 28 words and 29 words will cause the game to flash back or make mistakes,

**Pull request merged**
