### PR TITLE
Added CRC's for the latest updates.

### PR DESCRIPTION
**Pull request by EmuAl**
Added CRC's for the latest updates. hopefully it's done correctly this time, using vs2019 program.

### CODE REVIEW

**Comment by EmuAl** [comment]
so it looks better this time but still failed the CI, on assembly-info stuff, is this something i need to add ?

**Comment by Harmmmm** [comment]
Before you commit make sure it compiles on your pc and test your changes. ;)

You didn't added the new game versions to the GameID enum and didn't add the initfunctions for it.

**Comment by EmuAl** [comment]
thanks again for the pointers, i've added to the GameID.h file, just need to know where to look for initfunctions thing ?

**Comment by EmuAl** [comment]
looking at the initfunctions items in the sln, it seems there is nothing in there to add so it must go somewhere else

**Comment by EmuAl** [comment]
right so in the apm3.cpp thats where the functions go ?

**Comment by Harmmmm** [comment]
> right so in the apm3.cpp thats where the functions go ?

yes

**Comment by Poliwrath** [comment]
Goonya Fighter doesn't have patches, so you don't need to give it a special game ID. You can use either ``RollingGunner20`` or ``RollingGunner21``, eventually we should get rid of duplicate game IDs.

Unfortunately, Pengo DOES have patches, so you'd have to figure out how to port them if the addresses are different.

**Comment by EmuAl** [comment]
i think i've all the errors, i've added the updates and built the files and have them working here, the only thing thats got me is the patch thing for pengo, i don't understand where or how to get the numbers that are added in the patch on original pengo

**Comment by Poliwrath** [comment]
It's difficult to explain it, those are code patches. You can just remove pengo from your PR if you want.

**Comment by EmuAl** [comment]
yep i'll remove pengo as i don't know anything like that yet.

**Comment by Poliwrath** [comment]
Yeah, that's fine.

**Pull request closed without merging**
