### PR TITLE
Fixing eX-Board width/height to 1920/1080 for fullscreen mode.

### PR DESCRIPTION
**Pull request by adamgp**
Experimented with expanding the fullscreen display to FullHD resolution - but how to use the current screen dimensions instead than this hardcoding?

### CODE REVIEW

**Comment by Poliwrath** [comment]
``EnumDisplaySettings`` is what you want, I think
Also, I don't think this is the best way to fix this. Maybe changing ``BackBufferWidth``/``BackBufferHeight`` in CreateDevice works? (I don't know much DX stuff)

**Comment by adamgp** [comment]
Basic fullscreen fix until someone has the skills to do this in a manner which respects the original Aspect Ratio.

**Comment by Nezarn** [comment]
Added a proper fix\hack, pls test every exboard game (test menu should save now too)

**Comment by Poliwrath** [comment]
I don't think this is necessary now because of 7fdfe40873afee6827a8b10222bd077a6ffffc0c

**Pull request closed without merging**
